// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace TestUnit
{

    [TestFixture]
    public class ValMsgObrigatoriaTest
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void valMsgObrigatoria()
        {
            driver.Navigate().GoToUrl("https://livros.inoveteste.com.br/contato/");
            try
            {
                Thread.Sleep(4000);
            }
            catch (Exception e)
            {
                Console.WriteLine("{0} Exception caught.", e);
            }
            driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
            driver.FindElement(By.CssSelector(".wpcf7-submit")).Click();
            try
            {
                Thread.Sleep(4000);
            }
            catch (Exception e)
            {
                Console.WriteLine("{0} Exception caught.", e);
            }
            Assert.That(driver.FindElement(By.CssSelector(".your-name > .wpcf7-not-valid-tip")).Text, Is.EqualTo("O campo é obrigatório."));
            Assert.That(driver.FindElement(By.CssSelector(".your-email > .wpcf7-not-valid-tip")).Text, Is.EqualTo("O campo é obrigatório."));
            Assert.That(driver.FindElement(By.CssSelector(".your-subject > .wpcf7-not-valid-tip")).Text, Is.EqualTo("O campo é obrigatório."));
            Assert.That(driver.FindElement(By.CssSelector(".your-message > .wpcf7-not-valid-tip")).Text, Is.EqualTo("O campo é obrigatório."));
        }
    }
}
